// --------------------------------------------------------------
// EDIT ONLY THESE
__EXEC(ark_re_camouflage = "woodland";)
//__EXEC(ark_re_camouflage = "desert";)
//__EXEC(ark_re_camouflage = "snow";)
// --------------------------------------------------------------

__EXEC(ark_hull3_factionConfigs = missionconfigFile >> "Hull3" >> "Faction";)
__EXEC(ark_hull3_factionConfigs = "true" configClasses ark_hull3_factionConfigs;)
__EXEC(ark_re_factionConfigs = [];)
__EXEC({ ark_re_factionCamouflage = _x >> "camouflage"; ark_re_factionCamouflage = getArray ark_re_factionCamouflage; ark_re_hasMatchingCammo = ark_re_camouflage in ark_re_factionCamouflage; if ark_re_hasMatchingCammo then { ark_re_factionConfigs pushback _x; }; } foreach ark_hull3_factionConfigs;)

__EXEC(ark_re_attacker_config = ark_re_factionConfigs select random floor count ark_re_factionConfigs;)
__EXEC(ark_re_attacker_faction = configName ark_re_attacker_config;)
__EXEC(ark_re_attacker_side = ark_re_attacker_config >> "side";)
__EXEC(ark_re_attacker_side = toUpper getText ark_re_attacker_side;)
__EXEC(ark_re_attacker_sidePrefix = "I";)
__EXEC(ark_re_attacker_sidePrefixMatch = ark_re_attacker_side == "WEST";)
__EXEC(if ark_re_attacker_sidePrefixMatch then { ark_re_attacker_sidePrefix = "B"; };)
__EXEC(ark_re_attacker_sidePrefixMatch = ark_re_attacker_side == "EAST";)
__EXEC(if ark_re_attacker_sidePrefixMatch then { ark_re_attacker_sidePrefix = "O"; };)
__EXEC(ark_re_attacker_rolePrefix = ark_re_attacker_config >> "rolePrefix";)
__EXEC(ark_re_attacker_rolePrefix = getText ark_re_attacker_rolePrefix;)
__EXEC(ark_re_attacker_gear = ark_re_attacker_config >> "gear";)
__EXEC(ark_re_attacker_gear = getText ark_re_attacker_gear;)
__EXEC(ark_re_attacker_uniform = ark_re_attacker_config >> "uniform";)
__EXEC(ark_re_attacker_uniform = getText ark_re_attacker_uniform;)
__EXEC(ark_re_attacker_name = ark_re_attacker_config >> "name";)
__EXEC(ark_re_attacker_name = getText ark_re_attacker_name;)

__EXEC(ark_re_differentSideFactionConfigs = [];)
__EXEC({ ark_re_factionSide = _x >> "side"; ark_re_factionSide = getText ark_re_factionSide; ark_re_isDifferentSide = ark_re_attacker_side != ark_re_factionSide; if ark_re_isDifferentSide then { ark_re_differentSideFactionConfigs pushback _x; }; } foreach ark_re_factionConfigs;)

__EXEC(ark_re_defender_config = ark_re_differentSideFactionConfigs select random floor count ark_re_differentSideFactionConfigs;)
__EXEC(ark_re_defender_faction = configName ark_re_defender_config;)
__EXEC(ark_re_defender_side = ark_re_defender_config >> "side";)
__EXEC(ark_re_defender_side = toUpper getText ark_re_defender_side;)
__EXEC(ark_re_defender_sidePrefix = "I";)
__EXEC(ark_re_defender_sidePrefixMatch = ark_re_defender_side == "WEST";)
__EXEC(if ark_re_defender_sidePrefixMatch then { ark_re_defender_sidePrefix = "B"; };)
__EXEC(ark_re_defender_sidePrefixMatch = ark_re_defender_side == "EAST";)
__EXEC(if ark_re_defender_sidePrefixMatch then { ark_re_defender_sidePrefix = "O"; };)
__EXEC(ark_re_defender_rolePrefix = ark_re_defender_config >> "rolePrefix";)
__EXEC(ark_re_defender_rolePrefix = getText ark_re_defender_rolePrefix;)
__EXEC(ark_re_defender_gear = ark_re_defender_config >> "gear";)
__EXEC(ark_re_defender_gear = getText ark_re_defender_gear;)
__EXEC(ark_re_defender_uniform = ark_re_defender_config >> "uniform";)
__EXEC(ark_re_defender_uniform = getText ark_re_defender_uniform;)
__EXEC(ark_re_defender_name = ark_re_defender_config >> "name";)
__EXEC(ark_re_defender_name = getText ark_re_defender_name;)

__EXEC(ark_re_overviewText = ark_re_attacker_name + " attacks a position defended by " + ark_re_defender_name + " | Slot 1:1 | Deploy";)
